### ISSUE TITLE
Issue loading in previously saved allele_table

### ISSUE THREAD

**Issue by oligomyeggo** [YosefLab/Cassiopeia#126]
Hi @mattjones315, I am working through the new [Reconstructing trees with Cassiopeia tutorial](https://cassiopeia-lineage.readthedocs.io/en/testdeployment/notebooks/reconstruct.html) with my GESTALT data, and so far mostly good (I think). However, I am having a problem with `cassiopeia.pp.compute_empirical_indel_priors` if I open a new jupyter notebook and load in an `allele_table` that was saved in my preprocessing notebook:

My code:
```
indel_priors = cassiopeia.pp.compute_empirical_indel_priors(allele_table, grouping_variables=['intBC', 'lineageGrp'])
```

The error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-2d54866e2893> in <module>
----> 1 indel_priors = cassiopeia.pp.compute_empirical_indel_priors(allele_table, grouping_variables=['intBC', 'lineageGrp'])

~/Desktop/code/Cassiopeia/cassiopeia/preprocess/utilities.py in compute_empirical_indel_priors(allele_table, grouping_variables, cut_sites)
    689     for g in groups.index:
    690 
--> 691         alleles = np.unique(np.concatenate(groups.loc[g].values))
    692         for a in alleles:
    693             if "none" not in a.lower():

<__array_function__ internals> in unique(*args, **kwargs)

~/.pyenv/versions/3.6.12/lib/python3.6/site-packages/numpy/lib/arraysetops.py in unique(ar, return_index, return_inverse, return_counts, axis)
    259     ar = np.asanyarray(ar)
    260     if axis is None:
--> 261         ret = _unique1d(ar, return_index, return_inverse, return_counts)
    262         return _unpack_tuple(ret)
    263 

~/.pyenv/versions/3.6.12/lib/python3.6/site-packages/numpy/lib/arraysetops.py in _unique1d(ar, return_index, return_inverse, return_counts)
    320         aux = ar[perm]
    321     else:
--> 322         ar.sort()
    323         aux = ar
    324     mask = np.empty(aux.shape, dtype=np.bool_)

TypeError: '<' not supported between instances of 'float' and 'str'
```

I am not sure why this is happening. Using the same `allele_table` in my preprocessing notebook I am able to run `cassiopeia.pp.compute_empirical_indel_priors` with no issue. And I guess related to this, is it appropriate for GESTALT data to be using `compute_empirical_indel_priors`? Based on the tutorial, it sounds like this might be something that is unique to your system with intBCs, and yet if I don't run `compute_empirical_indel_priors` then I have issues downstream generating the `character_matrix`. And if I tweak `indel_priors = cassiopeia.pp.compute_empirical_indel_priors(allele_table, grouping_variables=['intBC', 'lineageGrp'])` to instead be `indel_priors = cassiopeia.pp.compute_empirical_indel_priors(allele_table, grouping_variables=['lineageGrp'])` (removing intBC since the GESTALT system doesn't have them, so perhaps I wouldn't want to group by them) then I get a tree that looks weird (almost no branches or nodes or leaves). This is using the `vanilla_greedy` and 'nj' neighbor-joining solvers; I can't current use the `ilp-solver` because my Gurobi license has expired, but I will look into renewing that if it looks like the `ilp-solver` will  be the most useful to me.

All that said, I ran through the rest of your tutorial as a continuation of my preprocessing steps in the same notebook and everything seems to be working for the most part. I am getting one other error and I have a few questions, and was not sure if I should open them all as separate issues, or keep them running in this thread as a potential singular resource to troubleshoot GESTALT data at the reconstruction stage.

Thanks!

**Comment by mattjones315** [comment]
Hi @oligomyeggo ,

Thanks for proceeding to the next step in the Cassiopeia pipeline and posting this issue! My best guess as to why this issue is occurring is because you have "missing" data in your cut-sites. As we discussed in your previous issue (#109), the alignment parameters that work for our molecular recorder technology might not be optimized for GESTALT datasets. This nuance causes some cut-sites to contain `NaN` values, indicating missing data.

In my experience, `NaN`'s can behave differently if you're working with a DataFrame that you created or read in. Specifically, sometimes when you read in a DataFrame that has 'NaN's, or missing data, these values will be cast to a float-based `nan` value. With our technology, because the alignment strategy works for us invariable, we don't have any 'NaN's in the allele table. So, I believe this is what is causing the issue here.

I believe the following will fix your problem here:

(1) Replace all missing data in your allele table with a string "Missing".
(2) Run `compute_empirical_indel_priors` or `convert_allele_table_to_character_matrix`. 
(3) Then, replace the unique integer representing the state "Missing" in each character to -1. You can do this with the the object `state2indel` that is returned by `convert_allele_table_to_character_matrix`. This is a nested dictionary that stores the state-indel mappings for each character (you can read more about [here](https://cassiopeia-lineage.readthedocs.io/en/latest/api/reference/cassiopeia.pp.convert_alleletable_to_character_matrix.html#cassiopeia.pp.convert_alleletable_to_character_matrix)). Something like this would work:

```
character_matrix, priors, state2indel = cas.pp.convert_allele_table_to_character_matrix(...)
for character in state2indel.keys():
    for state in state2indel[character].keys():
        if state2indel[state] == 'Missing':
           character_matrix.iloc[:,character].replace(state, -1)
```

Lastly, I'll say that while here you probably won't learn anything from `cas.pp.compute_emprical_indel_priors`, in the future when you have several datasets from different embryos, you will absolutely be able to use this procedure. This procedure will evaluate how many times a particular indel appeared across embryos -- since each embryo is independent, you can get an idea of each indel's probability of appearing. 

Let me know how this goes, and if this fixes your problem. Good luck!

**Comment by oligomyeggo** [comment]
Hi @mattjones315, thanks for your quick response!

The "missing" data in the cut-sites did seem to be the issue. When I replaced all of my missing data in my `allele_table` with `"Missing"`, I was able to load the `allele_table` into a new jupyter notebook and run `compute_empirical_indel_priors` with no problem. I did have a little issue running the code you provided to replace `"Missing"` with `-1`. The code as is returned the following error: `RuntimeError: dictionary changed size during iteration`, but I believe that the following adjustment worked (though definitely correct me if I'm using `.copy()` wrong!):

```
for character in state2indel.copy().keys():
    for state in state2indel[character].copy().keys():
        if state2indel[state].copy() == 'Missing':
           character_matrix.iloc[:,character].replace(state, -1)
```

And that makes sense, so far as `compute_empirical_indel_priors` not being particularly informative in my specific situation since I am working with a dataset from only "one" embryo (or what I am pretending is one embryo). But am I correct in thinking that `compute_empirical_indel_priors` is still a step I need to run in order to generate the `character_matrix`?

While we're on the subject of indels and priors, does it make sense to have my most frequent indels all having the same counts and frequencies (see indel_priors.png screenshot)? And does it makes sense to have the same value for all of the priors in my prior dictionary (see priors.png screenshot)? I am not quite sure what might look a little funny because I am working with the GESTALT system as opposed to your intBC-based system (and so some things will just be different due to the two different systems, but things are working), and what might look funny because something isn't working with my data (as in something isn't being computed correctly).

![indel_priors](https://user-images.githubusercontent.com/13051802/128367032-0b787b80-b7a5-4123-a305-0412ac886cce.png)
![priors](https://user-images.githubusercontent.com/13051802/128367036-696d3168-f872-44ce-9882-b60cb6f74a80.png)

**Comment by mattjones315** [comment]
Hey @oligomyeggo,

Great, that's awesome it fixed your problem! Apologies that the code did not work -- but glad you figured out a fix. I'm frankly not sure why this was happening. One note though -- I believe you'll need to add `inplace=True` to `replace`. Otherwise, your resulting character matrix will not have `-1` marking missing data. To be clear, this is the line you want, I believe:

```
character_matrix.iloc[:,character].replace(state, -1, inplace=True)
```

Also, you actually do not need to compute the indel priors before creating the character matrix. This line should work just fine:

```
cas.pp.convert_allele_table_to_character_matrix(allele_table, ..., mutation_priors=False,...)
```
This will still return a priors dictionary but it have anything in it.

Finally, the fact that all of your indels have the same count is exactly what I'd expect. Basically, the indel prior is calculated as:

```
p(indel) = (# times the indel occurs in an independent group) / (# groups)
```
So, every indel has the same count because you can't stratify your cells by embryo -- in other words, there is only one group. When you _can_ stratify by embryo, you can group cells by embryo expect to see some differences between the indel counts and thus have a better idea of the priors.  Does that make more sense?

Please don't hesitate to reach out again if you have any other questions!

**Comment by oligomyeggo** [comment]
Thanks @mattjones315, your explanation makes sense to me! I appreciate you clarifying all of that.

I have run into another hiccup now, though. Following your suggestions in the post above, I adjusted my `character_matrix` using `inplace=True` and dropped the `compute_empirical_indel_priors` step (and set `mutation_priors=None` in the `convert_allele_table_to_character_matrix` call). However, now I cannot run `vanilla_greedy.solve(cas_tree)`. I get the following error:

```
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-88-5403c0bf07f6> in <module>
      3 
      4 # reconstruct the tree
----> 5 vanilla_greedy.solve(cas_tree)

~/Desktop/code/Cassiopeia/cassiopeia/solver/GreedySolver.py in solve(self, cassiopeia_tree, layer)
    150             unique_character_matrix,
    151             weights,
--> 152             cassiopeia_tree.missing_state_indicator,
    153         )
    154 

~/Desktop/code/Cassiopeia/cassiopeia/solver/GreedySolver.py in _solve(samples, tree, unique_character_matrix, weights, missing_state_indicator)
     98                     samples,
     99                     weights,
--> 100                     missing_state_indicator,
    101                 )
    102             )

~/Desktop/code/Cassiopeia/cassiopeia/solver/VanillaGreedySolver.py in perform_split(self, character_matrix, samples, weights, missing_state_indicator)
    109                             if (
    110                                 mutation_frequencies[character][state]
--> 111                                 * weights[character][state]
    112                                 > best_frequency
    113                             ):

KeyError: 1
```

I was able to run `vanilla_greedy.solve(cas_tree)` when I computed the indel priors, so I wonder if something is now missing that I need to add back in? Also, I noticed that when I included the `collapse_mutationless_edges=True` option in the run where I computed indel priors, I got the following error:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-319-db8cf3c0e957> in <module>
      3 
      4 # reconstruct the tree
----> 5 vanilla_greedy.solve(cas_tree, collapse_mutationless_edges=True)

TypeError: solve() got an unexpected keyword argument 'collapse_mutationless_edges'
```

If I removed `collapse_mutationless_edges=True` then `vanilla_greedy.solve` was able to run. Not sure if this is just due to me not having have pulled the latest updates from the Master branch or not, but figured I would mention it since I am now stuck on that step.

Thanks again! You have been tremendously helpful!

**Comment by mattjones315** [comment]
Hi @oligomyeggo,

Great, glad that helped out!

How are you creating the tree? If you are doing `cas_tree = cas.data.CassiopeiaTree(character_matrix, priors=priors)` with the empty priors dictionary you created, then any solver will break (we are currently using the priors if it exists in the CassiopeiaTree). Even though the priors dictionary is empty, it's not `None` and will break. I'll make a note of this for my next PR.

Regarding the code breaking at `collapse_mutationless_edges` -- I believe this is because you might be using a codebase that is _slightly_ out of date compared to the tutorial that we posted because this change was in a recent PR (as you can see, things are changing quite rapidly!). The good news is that the notebooks should be stable with respect to the `master` branch now. If you want to pull from the master branch and re-install, you should be good to go here!

Let me know if you run into any other issues!

**Comment by oligomyeggo** [comment]
Hi @mattjones315, thanks so much! I was creating the tree using `cas_tree = cas.data.CassiopeiaTree(character_matrix, priors=priors)`. I switched this to `cas_tree = cas.data.CassiopeiaTree(character_matrix, priors=None)` and that fixed it. I also updated to the `master` branch which fixed the `collapse_mutationless_edges` issue, so seems like all the code is now running as expected with my GESTALT data for the reconstruction step. Now for the hard part I think - trying to figure out if the trees I'm getting back make any sort of biological sense. I'll open a new issue if they look problematic to discuss that there; I'm guessing if things look funky it might be due to alignment like we discussed in issue #109 and so I might need to revisit that. Thanks again!!

**Comment by mattjones315** [comment]
Hi @oligomyeggo,

Great! Glad everything seems to be working now. I'm currently working through and fixing up some of the stuff that we noticed in your previous issue (including throwing a warning if there are missing values in the alleles after `cas.pp.call_alleles`). Hopefully these things will make it easier for the next GESTALT user!

When you're ready to visualize some trees, you can use our `cas.pl` library which really only has utilities for iTOL. But if you create an account on iTOL, we've found this package to be _really_ useful for all of our tree visualizations! As always, please do not hesitate to reach out with any issues or questions you encounter in the future.

I'm going to go ahead and close this issue now since it sounds like we resolved these problems - good luck!
