### ISSUE TITLE
Possible bug  in `cas.pl.upload_and_export_itol`

### ISSUE THREAD

**Issue by tzeitim** [YosefLab/Cassiopeia#193]
It seems that the `itol_utilities` module requires a `Path` object. Passing a string results into an error:

```
itol.py:38, in Itol.add_file(self, file_path)
     34 def add_file(self, file_path: Path) -> None:
     35     """
     36     Add a file to be uploaded, tree or dataset
     37     """
---> 38     if not file_path.is_file():
     39         raise IOError('%s is not a file' % file_path)
     40     self.files.append(file_path)

AttributeError: 'str' object has no attribute 'is_file'
```

By passing a `Path` object this gets solved, e.g.

```
# in itol_utilities.py
# from pathlib import Path

itol_uploader = Itol()
itol_uploader.add_file(
    Path(os.path.join(temporary_directory, "tree_to_plot.tree"))

)
```

Thanks

**Comment by YushaLiu** [comment]
I have got the same problem... I'm new to Python. Is there a way to successfully call cas.pl.upload_and_export_itol without modifying the source code? @tzeitim

**Comment by tzeitim** [comment]
@YushaLiu - I am afraid that the only way to do this is to change the source code. Perhaps the best would be to change the code from `itol_utilities` and not `cassiopeia` in the short run, since there are many invocations to across `cassiopeia` that would require more changes. That said, I think that the long term solution is to adapt `cassiopeia` to convert the objects into `Path`s.

If you are not experienced with coding this is a good opportunity to gain some confidence. The task (change the source code) might sound daunting at first but in this case it is a rather simple one.

**Comment by YushaLiu** [comment]
Sorry that i just saw your response. Thanks very much! @tzeitim

**Comment by mattjones315** [comment]
Hi all, 

Sincerest apologies for not getting around to this sooner. I'm finally looking into this and have made the suggested changes in #197.  However, I'm afraid I don't have an iTOL license anymore meaning I cannot test this new code. Would one of you be able to pull this code and test this with your dataset?

As a general note -- I'm tempted to deprecate this functionality because I won't want to pay a personal subscription for iTOL just to maintain this code. So, while this might fix the current issue, I won't be able to guarantee that future issues raised by changes in other packages will be fixed int his particular module. However, I welcome any contributions from your end if you are interested in helping maintain this functionality! As I'm sure you've seen, we've transitioned to using `cas.pl.plot_matplotlib` and `cas.pl.plot_plotly` for tree plotting, I hope this alternative functionality is helpful for you.

Best,
Matt

**Comment by YushaLiu** [comment]
I have pulled the update related to plotting in iTOL and tested this on my dataset, and it worked well.

**Comment by mattjones315** [comment]
Great, thank you @YushaLiu! I'll go ahead and merge it in then.
