### ISSUE TITLE
How to use Cassiopia to analyze bulk DNA sequencing data

### ISSUE THREAD

**Issue by yuangh16** [YosefLab/Cassiopeia#236]
Before single cell experiments, we performed bulk DNA sequencing to make some QC. I am wondering is it possible to use Cassiopia to analyze bulk DNA sequencing data, which can give us the number intergration barcodes and editting efficiency at different target editting sites ?

**Comment by mattjones315** [comment]
Hi @yuangh16,

Thanks for your question and apologies for the delay. You should be able to use Cassiopeia's functionality for performing some parts of the analysis, but some steps will not work because we assume you have UMIs attributed to each read.

However, you can still probably use the `cas.pp.align_sequences` and `cas.pp.call_alleles` functionality to detect edits in your reads, after hacking together a molecule table with "dummy" cellBCs and UMIs.

Please let me know if you have any questions or run into any issues. I'll go ahead and close this issue but please feel free to re-open if I can be of any further help with Cassiopeia.
